apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.hooks.migrate.name }}-migrate-{{ .Values.hooks.migrate.revision }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Running DB migration...'; sleep 3; echo 'Done'"]