apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
  namespace: team-alpha
spec:
  containers:
  - image: postgres:15
    name: postgres-client

    command:
      - sleep
      - infinity

    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
