apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: problem-three-pvc
  namespace: team-alpha
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: problem-three-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/tmp
    type: DirectoryOrCreate

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: problem-three-pod-one
  name: problem-three-pod-one
  namespace: team-alpha
spec:
  nodeSelector:
    kubernetes.io/hostname: calico-lab-control-plane
  containers:
  - image: busybox
    name: problem-three-pod-one
    command:
      - sh
      - -c
    args:
      - |
        echo "Hello from problem-three-pod-one" > /mnt/data/file.txt
    resources: {}
    volumeMounts:
      - mountPath: /mnt/data
        name: my-problem-three-pv
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  volumes:
    - name: my-problem-three-pv
      persistentVolumeClaim:
        claimName: problem-three-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: problem-three-pod-two
  name: problem-three-pod-two
  namespace: team-alpha
spec:
  containers:
  - image: busybox
    name: problem-three-pod-two
    command:
      - sh
      - -c
    args:
      - |
        echo "Hello from problem-three-pod-two" > /mnt/data/file.txt
    resources: {}
    volumeMounts:
      - mountPath: /mnt/data
        name: my-problem-three-pv
  volumes:
    - name: my-problem-three-pv
      persistentVolumeClaim:
        claimName: problem-three-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}