apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: problem-one-pvc
  namespace: team-alpha
spec:
  storageClassName: nonexistentclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: problem-one-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nonexistentclass
  hostPath:
    path: /tmp/data/
    type: DirectoryOrCreate