apiVersion: v1
kind: Namespace
metadata:
  labels:
    team: alpha
  name: team-alpha

---

apiVersion: v1
kind: LimitRange
metadata:
  name: team-alpha-limits
  namespace: team-alpha
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 256Mi
    defaultRequest: # this section defines default requests
      cpu: 100m
      memory: 128Mi
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: 50m
    type: Container

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-alpha-quota
  namespace: team-alpha
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "8"