apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: null
  name: api-pdb
  namespace: team-alpha
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis-check
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
