apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded  # delete Job after it completes
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ahshicorp/http.echo:latest
          command: ["-text", "Hello, I am a PostSync Job"]