apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpha-pod-2
  name: alpha-pod-2
  namespace: team-alpha
spec:
  containers:
  - image: nginx:1.25
    name: alpha-pod-2
    resources: {}
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: my-pvc-volume
  volumes:
    - name: my-pvc-volume
      persistentVolumeClaim:
        claimName: alpha-pvc-2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}