apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-pvc-3
  namespace: team-alpha
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi