apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/iamakshu29/devops-cicd-toolchain.git
    targetRevision: main
    path: Reference_Project/petclinic-app

    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true