apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
  namespace: team-alpha
spec:
  containers:
  - image: nginx:1.25
    name: test-pod
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secrets
        readOnly: true

    env:
    - name: nginx-secret
      valueFrom:
        secretKeyRef:
            name: test-secret
            key: password
            
    resources: {}

  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
