apiVersion: v1
data:
  CART_SERVICE_ADDR: cartservice:7070
  CHECKOUTSERVICE_PORT: "5050"
  CURRENCY_SERVICE_ADDR: currencyservice:7000
  EMAIL_SERVICE_ADDR: emailservice:5000
  PAYMENT_SERVICE_ADDR: paymentservice:50051
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
  SHIPPING_SERVICE_ADDR: shippingservice:50051
kind: ConfigMap
metadata:
  name: checkoutservice-config
  namespace: google-microservice
