apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shared-pod
  name: shared-pod
spec:
  containers:
  - image: busybox:latest
    name: app
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
    command:
      - sh
      - -c
    args: 
      - |
        while true; do
          echo "$(date)" >> /shared/app.log
          sleep 5
        done
    resources: {}
  - image: busybox:latest
    name: log-shipper
    volumeMounts:
      - name: shared-volume
        mountPath: /shared
    command:
      - sh
      - -c
    args:
      - tail -f /shared/app.log
    resources: {}
  volumes:
    - name: shared-volume
      emptyDir: {}

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
