apiVersion: v1
kind: Secret
metadata:
  name: fake-pull-secret
  namespace: prac
type: kubernetes.io/dockerconfigjson
# base64 of: {"auths":{"registry.example.com":{"username":"fake-user","password":"fake-password","auth":"ZmFrZS11c2VyOmZha2UtcGFzc3dvcmQ="}}}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6ImZha2UtdXNlciIsInBhc3N3b3JkIjoiZmFrZS1wYXNzd29yZCIsImF1dGgiOiJabUZyWlMxMWMyVnlPbVpoYTJVdGNHRnpjM2R2Y21RPSJ9fX0=
