apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-postgres-pod
  name: test-postgres-pod
  namespace: team-alpha
spec:
  containers:
  - image: postgres:15
    name: test-postgres-pod
    resources: {}
    volumeMounts:
      - name: restored-data
        mountPath: /var/lib/postgresql/data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: restored-data
      persistentVolumeClaim:
        claimName: postgres-restored
status: {}
