apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boutique-app
  name: boutique-app
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: boutique-app
  strategy: {}
  template:
    metadata:
      labels:
        app: boutique-app
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo
        name: microservices-demo
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources: {}
