apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: check-pod
  name: check-pod
spec:
  containers:
  - image: nginx:1.23
    name: check-pod
    resources:
      requests:
        cpu: "7"
        memory: 1.5Gi
      limits:
        cpu: "10"
        memory: 2Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
