apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: beta-app
  name: beta-app
  namespace: team-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beta-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: beta-app
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        startupProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        resources: {}
status: {}
