frontend:
  appName: frontend 
  replicas: 3
  container:
    image: nginx
    imageTag: alpine
    imageName: nginx
  resources:
    limits:
      cpu: 150m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 256Mi
  
  service:
    type: NodePort
    port: 80
    targetPort: 80

backend:
  appName: backend
  replicas: 1
  container:
    image: hashicorp/http-echo
    imageTag: latest
    imageName: http-echo
    args: ["-text","Hello from Backend"]
  resources:
    limits:
      cpu: 150m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 256Mi

  service:
    type: ClusterIP
    port: 81
    targetPort: 5678







