apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: monitoring-reader
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get