apiVersion: v1
data:
  secret_key: c2VjcmV0X3ZhbHVl
kind: Secret
metadata:
  creationTimestamp: "2026-08-01T19:59:11Z"
  name: test-secret
  namespace: team-alpha
  resourceVersion: "362602"
  uid: de8900ed-0b63-49aa-a481-8fb7b7460c65
type: Opaque