apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: postgres
  name: postgres
spec:
  containers:
  - image: postgres:15
    name: postgres
    resources: {}
    env:
      - name: APP_ENV
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: color
      - name: POSTGRES_PASSWORD_FILE # required value to run postgres container
        value: /etc/secrets/db-password
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secrets
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
